spring.application.name=demo
spring.output.ansi.enabled=always
spring.profiles.default=dev

spring.jpa.defer-datasource-initialization=true

server.port=5000

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000}
app.security.user.name=${APP_ADMIN_USERNAME:admin}
app.security.user.password=${APP_ADMIN_PASSWORD:admin}

management.endpoints.web.exposure.include=health,info


