spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.h2.console.enabled=false
spring.jpa.hibernate.ddl-auto=validate

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS}
app.security.user.name=${APP_ADMIN_USERNAME}
app.security.user.password=${APP_ADMIN_PASSWORD}
